In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np

data_train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data project 1 AI Indonesia/data_train.csv')
data_test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data project 1 AI Indonesia/data_test.csv')

In [ ]:
data_train.head()

,tweet,sentimen,clean_tweet
0,Komentarnya bagus. Tapi alangkah indshnya jika...,positif,komentar bagus alangkah indshnya ibu bilang jo...
1,Jokowi: Pertumbuhan Ekonomi >5% Harus Disyukur...,netral,jokowi tumbuh ekonomi syukur jangan_kufur nikm...
2,"Buat yang ciwi-ciwi, mau harga skincare turun?...",netral,buat ciwiciwi harga skincare turun tusuk prabo...
3,"Alhamdulillah,penutup terkeren dr @prabowo Da...",positif,alhamdulillahpenutup keren prabowo sandiuno ti...
4,"Pun dari hal yang diutarakan Jokowi kemaren, e...",netral,utara jokowi kemaren esports sendiri memang be...

In [ ]:
data_test.head()

,tweet,sentimen,clean_tweet
0,"Bukan hanya kurang milenial, tapi memang dia s...",negatif,bukan_kurang milenial memang sama sekali tidak...
1,artinya presiden yg ke 6 tdk menerima gaji.pra...,positif,arti presiden tidak_terima gajiprabowo sandi l...
2,Kalau menurut saya bang @sandiuno dan bapak ...,positif,kalau bang sandiuno bapak prabowo mampu tempat...
3,Bukan hanya ekonomi aja Pak....namun kehidupan...,negatif,bukan_ekonomi paknamun hidup buruh korbanphkil...
4,"Gak ngaruh, jokowi mau ke kutub utara juga, ra...",negatif,gak_ngaruh jokowi kutub utara rakyat tau baran...

In [ ]:
sample_tweets = data_train['clean_tweet'].sample(10, random_state=42).to_list()
for i, clean_tweet in enumerate(sample_tweets, 1):
  print(f"Tweet ke-{i}: {clean_tweet}")

Tweet ke-1: rizal ramli ekonomi indonesia tumbuh persen kalau prabowo pilih
Tweet ke-2: akibat bapak jokowi hutang import amburadul ekonomi gak_tumbuh rakyat gak_punya duit buat makan jajan rakyat suruh main mobile legend presidensontoloyo
Tweet ke-3: pak jokowi ubah cara pandang ekonomi kini semua orang hubung indonesia jadi lebih produktif efisien menyatuputihjokowi
Tweet ke-4: orang luar negeri sangat harga prestasi laku jokowi negara sendiri banyak caci
Tweet ke-5: masyarakat pelosok bilang kalau prabowo jadi president indonesia perang segitunya fitnah sebar hancur ekonomi makro buat tetap april tps tusuk prabowo sandi
Tweet ke-6: soal ekonomi salah arah ekonomi ri untung kapitalis
Tweet ke-7: pak jokowi pak prabowo turun harga aqua cgv rb hmmmmmmmmm
Tweet ke-8: luarbiasa bangun infrastruktur era bapak moga infrastruktur bangun tunjang tumbuh ekonomi perata sosial republik indonesia semangat
Tweet ke-9: klarifikasi besar beliau harga lawan debat
Tweet ke-10: prabowo naik tax ratio jadi jokowi ekonomi shock pilpres jokowimaruf prabowosandi pajak

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y_train_enc = encoder.fit_transform(data_train['sentimen'])  # ['positif', 'negatif'] → [2, 0]
y_test_enc = encoder.transform(data_test['sentimen'])

In [ ]:
#TF-IDF Defaults
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_defaults = TfidfVectorizer()
x_train_tfidf = tfidf_defaults.fit_transform(data_train['clean_tweet'])
x_test_tfidf = tfidf_defaults.transform(data_test['clean_tweet'])

In [ ]:
feature_names = tfidf_defaults.get_feature_names_out()
print(f"\n   📝 Contoh fitur (10 pertama):")
print(f"   {feature_names[:10]}")

   📝 Contoh fitur (10 pertama):
   ['aa' 'aaamiin' 'aagympilihpr' 'aagympilihprabowo'
 'aagympilihprabowosandi' 'aamiin' 'aaminnnn' 'abadi' 'abah' 'abai']

In [20]:
#Menyimpan matrik hasil tf idf dan label encoder untuk efesiensi

import joblib
from scipy.sparse import save_npz, load_npz

all_data = {
    'x_train_tfidf': x_train_tfidf,
    'x_test_tfidf': x_test_tfidf,
    'encoder': encoder,
    'tfidf_defaults': tfidf_defaults,
    'y_train_enc': y_train_enc,
    'y_test_enc': y_test_enc,
    'feature_names': feature_names
}

joblib.dump(all_data, '/content/drive/MyDrive/Colab Notebooks/data project 1 AI Indonesia/Individual Project/TF-IDF&LogisticRegression/data/all_data.pkl')

['/content/drive/MyDrive/Colab Notebooks/data project 1 AI Indonesia/Individual Project/TF-IDF&LogisticRegression/data/all_data.pkl']